#!/usr/bin/env bash
# Install Nginx if not already installed
if ! command -v nginx &> /dev/null
then
    echo "Nginx not found. Installing..."
    apt-get update
    apt-get install nginx -y
fi

# Make sure nginx user exists
if ! id -u nginx &>/dev/null; then
  useradd -r nginx
fi

# Modify Nginx configuration file to run as nginx user
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Modify Nginx configuration file to listen on all active IPs on port 8080
sed -i '/listen \[::\]:80 default_server;/a listen [::]:8080 default_server;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a listen 8080 default_server;' /etc/nginx/sites-available/default

# Restart Nginx
systemctl restart nginx
