#!/usr/bin/env bash
#Set up firewall to only allow incoming traffic on ports 80, 443, and 22
sudo ufw enable -y
sudo ufw allow 443
sudo ufw allow 22
sudo ufw allow 80
sudo ufw default deny incoming
sudo ufw default allow outgoing
