#!/usr/bin/env bash
#Write a Bash script that transfers a file from our client to a server:

# check if there are enough parameters
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# set variables for the parameters
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$server_ip":~/

# check the exit code of scp
if [ $? -eq 0 ]; then
  echo "File transfer successful"
else
  echo "File transfer failed"
fi
