#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt update # update the package lists
sudo apt install nginx -y # install nginx with no prompts

# Nginx should be listening on port 80
sudo ufw allow 'Nginx HTTP' # allow incoming traffic on port 80

# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Holberton School
echo "Holberton School" | sudo tee /var/www/html/index.html # create an index.html file with the string Holberton School

# As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
# You can’t use systemctl for restarting nginx
sudo service nginx restart # restart nginx using service command