#!/usr/bin/env bash
# Install nginx if not already installed
sudo apt update 
sudo apt install nginx -y

# Create a file named index.html
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Holberton School" > /etc/nginx/html/index.html
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart